server:
  port: 8080

spring:
  application:
    name: auth-api

  mvc:
    apiversion:
      use:
        path-segment: 1

  config:
    activate:
      on-profile: local

  sql:
    init:
      mode: always
      platform: h2
      schema-locations: classpath:db/schema-h2.sql

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:EVENT_PLATFORM_DB;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s

logging:
  level:
    yjh.ontongsal.testing: DEBUG
    org.springframework.web: DEBUG

jwt:
  issuer: auth-api
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC64nHOIaEUpGZ8Ru6RrmKKF+EDweSK84N/hasZLGMTJ7ITr8GeQX3fTdcx6uFxTwj+M3Emg0z2r4SzbKIwohoXVTSeO013NKodKjDphj3mnnbd1feMlCDLXKaK2zJ+mvWGbD7x9hgFJKQzF798NBaVVutwsFEJFyIkMeojGE8LTTWLF+7z3jfqnT0njGiKYveuAB7OnNAGsdUw6UO994OgP7xMc2SqhGujeA2c+JzNr4EIypPPbge/f7l4e+RYl3tkDqCsgdPAm2hkLbkSPT+OZM4Tmq2G95CkSkiRQFNhnpKXpurkuSwwlqzsQkrMaZRTLuJD0TXGJOFf8Kz5Awn9AgMBAAECggEAEZWDTJHj371YQN+rstyY1cV8nPRLCYfzTekvbPIjbSBfCqf1RjhQHG+GjMijTbYFP2XRT7GRaRfUTjP6gfjx24aSdndXlc/IWDyQCmj6VtvlWbO4OlH1tyzDvtNasCIeCysRASAJ3CU5p4g+GPTahLkY9HfVwbU1HfkhJQw0fV7GY1jcLWivZBR9X4VdVRKcjsWsbNIcdjG04w7G9u7/00PHl2JxUSETPmAs6jSRuKZ9CTkHwDllm1NVYm5faO4D97bDpHi43IrEWT9YLBifbVYOAlvNFJBf4WSUrMV4/3ejEMt7LlPFPCSFdPn+T0wv1DMHgDxUT/KT7RckQQIbQQKBgQD9zIQB/JoGBUv7UBCmW583HauQczEGuzbhAlY7SaHMgTuTXcXO+3eLBAwT03PybcMJtdKG51qKkwyoDEBk7DkDKu2AMemG2P9g6cLPvPCdegWCco9DANXgoK7IZWmN0v0b/fOxygsTez0KRa1E5m+9YQyInqi78GDvcJ3YQu6DawKBgQC8gV2cMvq6u08SP4X8VfUatfd+19QWAKEnIYkvRmMeQDYxGqIQa7q6YpFedEznu8eyUi+KdpNQNRyvzh510hr6cWkO3/oOHUM/xbj3vMF12/MVedhs5mt/+3OG4/HmKm+sL+E5GHcU/gMVkb9l9gNw5tswU5AKy4QESCN7GS/qNwKBgBTzZwpK8eQBV+5dA6LX+WKxXlJEUA3AMp2MddXbFDIvkN1vZj7Z31pocR7J285tZSZODhz4yC6cSPUuXbp3DZXHW2eztxVcoGg9o8lGTY6SXhYQoubjEMTEPuloBbihbCd9ZTqN9TAcgkNw0QbZBuxZMJGulzs8cqQRZdZOYCYVAoGBAJ7JhjX+R3AmOfwQIGgnbBj88Sca3R9PlnAk8q8s5m9j/YItghi89oTsZLGg2+tUJWpTipJjQcINi0WYJdZvjqQqBiouhy9+fNhqUF321SvXhBMyGRnamvEque0FdA3C72Cm0FxM/HplYem4ZPaZXdqrzDUQHsTJHEKTFbgqxk7PAoGAGonLafCHmtwK9YAvDgosOaKaH6r7mmR3JuZoKOw92hKzjL1PI2N+e6BvdrhHK1c2CMJTuna5vWZab8jhpmzsANsLD+YiNNPQEuTfG4klCemCm61s1wGAj0KKteFgNx5Jx7BrCCgCCu/z46jMEzCXpXhvyoaWZ5A6ABaIUGRxwoQ=
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuuJxziGhFKRmfEbuka5iihfhA8HkivODf4WrGSxjEyeyE6/BnkF9303XMerhcU8I/jNxJoNM9q+Es2yiMKIaF1U0njtNdzSqHSow6YY95p523dX3jJQgy1ymitsyfpr1hmw+8fYYBSSkMxe/fDQWlVbrcLBRCRciJDHqIxhPC001ixfu89436p09J4xoimL3rgAezpzQBrHVMOlDvfeDoD+8THNkqoRro3gNnPicza+BCMqTz24Hv3+5eHvkWJd7ZA6grIHTwJtoZC25Ej0/jmTOE5qthveQpEpIkUBTYZ6Sl6bq5LksMJas7EJKzGmUUy7iQ9E1xiThX/Cs+QMJ/QIDAQAB
  access-token-expiration: 30m  # 30분
  refresh-token-expiration: 14d # 14일
